export OBS_MAX_CAM_ID=6
export OBS_CAPTURE_TIME=5
export OBS_EXPECTED_CAMS=0
export OBS_EXPORT_URL=localhost:7000/observer
export OBS_EXPORT_SLEEP=10
export OBS_EXPORT_NAME=foobar
export OBS_IMPORT_PORT=7000
